### ISSUE TITLE
In-call status bar issue

### ISSUE THREAD

**Issue by ed-mejia** [xxxAIRINxxx/ARNModalTransition#1]
Hi, great port to Swift :)

I'm having an issue when a phone call gets in and you are in the middle of a transition..

1) Run the demo project on simulator
2) Choose bottom modal style
3) Toggle in-call status bar (command + Y )
4) Toggle in-call status bar (command + Y ) - again
5) Close the modal and watch the undesired effect

I'm still trying to find why this happen .

**Comment by xxxAIRINxxx** [comment]
Hi!,
I agreed.
I'm working in progress about that.

thanks.

**Comment by ed-mejia** [comment]
Hey @xxxAIRINxxx , Good to see you updated the library..

It seems the in-call status bar issue is no more, I tested this last code base and it works properly, however it looks like now it does not support that your fromVC could have a navigation controller.

Just open the main Story board and embed a navigation controller to your view controller, run and test a transition.

Additionally It seems now we need to have a lot of boilerplate in the presenter when previously you just set your desired parameters and now you need to declare presentationBeforeHandler, dismissalBeforeHandler, dismissalCompletionHandler inside of every viewcontroller that will need to present another viewcontroller modally using the Animator. 

Best regards!, and thanks for the great work you are doing here :)

**Comment by xxxAIRINxxx** [comment]
@ed-mejia 
Hi!
Thank you for the advice!
fixed this issue.

Best regards!
