### ISSUE TITLE
Need a feature that close the view when the tableview is scrolled to the top. 

### ISSUE THREAD

**Issue by DesmondPang** [xxxAIRINxxx/ARNModalTransition#2]
I think you can add a feature that close the view when the tableview is scrolled to the top. Just like the OverCurrentContext modal comments view in  Facebook App. When you keep scrolling up and reach to the top of the tableview, the swipe down gesture is called and then dismiss the modal view.

**Comment by xxxAIRINxxx** [comment]
Hi!

Thank you for the suggestion.
It is implemented here.
Please look.

[ARNInteractiveTransition](https://github.com/xxxAIRINxxx/ARNInteractiveTransition)

Best regards!
